#!/bin/bash
# program is for executing blend -s
# on the file PROMISING_CLUSTERS_HEIGHTS.txt
# which is produced from running good_clusters
#
# the file has to commented lines
# and the rest of the lines have
# cluster in column 1 &
# height of cluster in column 2

file=$1
echo $file

if [[ $file == /* ]]
then
	n_file="$HOME$file"
elif [[ $file == .* ]]
then
	tmp=${$file#?}
	echo $tmp
	n_file="$HOME$temp"
fi

declare -a heights
count="$(wc -l < $1)" 
echo $count
num=0
while IFS= read -r line
do
	word=$(echo $line | awk '{print $1;}')
	if [[ $word == "#" ]]
	then
		continue
	fi
        if [[ $num -lt $count ]]
	then
		ht=$(echo $line | awk '{print $2;}')
		heights+=($ht)
	fi	
done < $file

rm "synthesis_output.txt"
rm -rf all_merged_files
mkdir all_merged_files

for height in "${heights[@]}"
do
	echo $height
	short=$(awk "BEGIN {print $height-0.001}")
	tall=$(awk "BEGIN {print $height+0.001}")
	echo "blend -s $height $short"
	(blend -s $tall $short < /dev/null ) |& tee -a "synthesis_output.txt"
	cp ./merged_files/MERGING_STATISTICS.info ./all_merged_files/MERGING_STATISTICS_$height.info
done
